casbin/gorm-adapter

- adapter.go
fixed a bug with the specified table prefix
> fix:fixed a bug with the specified table prefix

- adapter.go
fix func loadpolicy can't load tablePrefix bug
> fix func loadpolicy with tablePrefix

- adapter.go
when new two or more adapter with tablePrefix
```go
var tablePrefix string
```
the global value will replace last adapter's tablePreifx
> fix when new multi adapter tableprefix bug

- adapter.go
- adapter_test.go
see also: https://github.com/casbin/casbin/issues/316
> feat: support empty policy field

- adapter.go
1) Utilize correct db error when the duplicate database is created 
2) As per http://v2.gorm.io/docs/conventions.html#TableName TableName() suppose to generate static names only (it could not be dynamic). The same source suggests a workaround that I implemented as DynamicCasbinRuleTable along with a scoped DB object for NewAdapterByDBUsePrefix.
3) As a result of 2. we can remove tablePrefix from global state
Signed-off-by: l1ghtman2k <aibek.zhil@gmail.com>
> Fix dynamic table names, and db error type

- adapter.go
Signed-off-by: 00LT00 <lightning@zerokirin.online>
Fix: https://github.com/casbin/gorm-adapter/issues/52
> style: format code

- adapter.go
- go.sum
> fix: add NewFilteredAdapter

- adapter.go
> increase column size to 100

- adapter.go
Fix: #67 
there is no need to change main version, for gorm supports auto migration
> fix: modify column p_type to ptype(#67)

- README.md
- adapter.go
- adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/pull/72
> add custom table support

- .github/workflows/ci.yml
- adapter.go
- adapter_test.go
- go.mod
- go.sum
Fix: #87 add github action ci and semantic release
plz do not use gorm version over 1.20.x, new version is still unstable.
> ci: github action ci and semantic release

- adapter.go
> fix: create index when using custom schema

- adapter.go
- adapter_test.go
- go.mod
- go.sum
Fix: #81 
Sorry for the delay.
> fix: add method UpdatePolicies

- adapter.go
- adapter_test.go
> fix: improve log support

- .github/workflows/ci.yml
- .releaserc.json
Signed-off-by: closetool <4closetool3@gmail.com>
Fix: https://github.com/casbin/gorm-adapter/pull/105#issuecomment-829811413
> fix: github action bot

- adapter.go
- adapter_test.go
> fix: new adapter can't change custom table name

- adapter.go
- adapter_test.go
- examples/rbac_with_domains_model.conf
- examples/rbac_with_domains_policy.csv
- go.mod
> fix: delete dependency of jackc/pgconn

- adapter.go
> fix: data can't contains comma ( , ) character

- adapter.go
- go.mod
- go.sum
related: [casbin#886](https://github.com/casbin/casbin/issues/886) [casbin#887](https://github.com/casbin/casbin/pull/887)
> feat: change LoadPolicyLine to LoadPolicyArray

- adapter.go
- adapter_test.go
> fix: change AddPolicies to batch insert

- adapter.go
> fix: RemoveFilteredPolicy don't check empty parameter

- README.md
> fix: update README.md about sqlite support

- adapter.go
Added support for saving policies in bulk. This speeds up reinserting all policies
> perf: execute saving all policies in batches of 1000

- adapter.go
Fix: https://github.com/casbin/gorm-adapter/issues/148
Signed-off-by: abingcbc <abingcbc626@gmail.com>
> feat: export manual db connection open and close

- adapter.go
- adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/issues/151
> fix: add column v6, v7

- adapter.go
- adapter_test.go
> feat: support NewAdapterWithoutAutoMigrate

- README.md
> docs: add sqlite support and turn off AutoMigrate description

- README.md
- adapter.go
- adapter_test.go
fix: https://github.com/casbin/gorm-adapter/issues/162#issuecomment-1168351113
> fix: remove the return value of TurnOffAutoMigrate

- adapter.go
> fix: db can't reuse

- adapter.go
- adapter_test.go
fix https://github.com/casbin/gorm-adapter/issues/177
> feat: support multiple filters for LoadFilteredPolicy

- adapter.go
Fix: https://github.com/casbin/gorm-adapter/issues/189
> fix: fix error handling in loadPolicyLine()

- .github/workflows/ci.yml
- .travis.yml
- adapter.go
- adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/issues/191
> feat: support SQL Server in gorm-adapter

- adapter.go
> feat: Add getter for DB

- adapter.go
Fixed the issue of growing primary keys in postgres
Fix: https://github.com/casbin/gorm-adapter/issues/223
> feat: fix Postgres primary keys growing

- adapter.go
the transaction is not concurrent safety, limit transaction concurrent and fail fast.
> feat: limit transaction concurrency

- adapter.go
- adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/issues/227#issuecomment-2024522886
> feat: add mutex lock to `Trasaction`

- adapter.go
> fix: initialize mutex before using

- adapter.go
> feat: add sqlite3 to error message

- adapter.go
- adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/issues/249
> feat: fix failure when calling SavePolicy within the Transaction method

- adapter.go
- adapter_test.go
- go.mod
- go.sum
Fix: https://github.com/casbin/gorm-adapter/issues/267
Fix: https://github.com/casbin/gorm-adapter/issues/262
> feat: add transaction support for nested and singular operations
