adapter.go
I create new adapter.
```
gormadapter.NewAdapter("sqlite3", "assets/database.db")
```
After i get panic `near "DATABASE": syntax error`. I think it's happened because connection string connect to database and not server.
I change https://github.com/casbin/gorm-adapter/blob/8e3239544c1cf4bab113bd2311d8d0842086abe8/adapter.go#L101
to `if a.driverName != "sqlite3"` and all is worked.
=> Compatible with sqlite3

adapter.go
This will prevent the following pannic: 
```
panic: SQL logic error [recovered]
panic: SQL logic error
```
That is caused by appending the db name to the source which triggers the panic on the following line: https://github.com/casbin/gorm-adapter/blob/5f0f4b5ecad7f5259de033c2765c1e9399b23034/adapter.go#L135
=> Don't append db name to sqllite when opening connection.

.travis.yml, adapter.go, adapter_test.go, examples/rbac_policy.csv
**Reason for support:**
In gorm, if you want to use [hooks](http://gorm.io/docs/hooks.html) for enforcing rules with casbin so you get cascading permissions, it's impossible to do so without degradation of performance when the DB grows in size.
Performance degradation occurs due to needing to create a new Enforcer on each callback, as the adaptor needs to be re-created with the db from the callback scope so rules can be added within the same transaction as the callback. This means on each callback, you have to fully load the policy which then tanks performance as your rule set grows.
**Workaround attempts:**
If you add a single Enforcer within the gorm scope to be used throughout each callback, then you hit race conditions with setting of adaptors for concurrent transactions.
If you …
=> Support for loading filtered policies

adapter.go, adapter_test.go, go.mod
Signed-off-by: 00LT00 <lightning@hdu.edu.cn>
Fix: https://github.com/casbin/gorm-adapter/issues/40
=> add user define database

adapter.go, adapter_test.go
A scenario is that when multiple adapters will be created under same database with method `NewAdapterByDBUseTableName`, in fact, this will create multiple tables with different name, current codes can't support this because the hard-code gorm uniqueIndex tag `unique_index` on `CasbinRule` will prevent creating unique index for other tables due to index name conflict. This PR is a proposal to support such scenario.
=> [feature request]: support to create multiple adapters under same database with method `NewAdapterByDBUseTableName`

README.md, adapter.go
=> fix: default table name

adapter.go
Right now from the following documentation user just knows that mysql can be used as the string while connecting to mysql
`	a, _ := gormadapter.NewAdapter("mysql", "mysql_username:mysql_password@tcp(127.0.0.1:3306)/") // Your driver and data source.
`
However if someone wants to use postgres then it is not clear what string should be used. Should that be "pg" or "pgsql" or "postgres" or "postgressql".
I had to navigate the code to find that out. Printing the supported DB name strings in error message so that user knows the valid options to use in  connection string would be helpful and this is what this commit attempts at doing.
So instead of printing 
> `"database dialect is not supported"`
it will print the passed in invalid option as well as the valid option list as follows. Also the …
=> fix: Printing the supported DB name strings in error message

adapter.go
PostgreSQL has one more schema  than other databases. When operating tables, there will be:    schema  . Table name
This will result in the following syntax when creating an index:
```code
CREATE UNIQUE INDEX idxweb.tb_auth_casbin_rule ON web.tb_auth_casbin_ rule (ptype,v0,v1,v2,v3,v4,v5)
```
This format with a point in the index name is not supported by PostgreSQL syntax.
```err
SQL ERROR [42601]: ERROR: syntax error at or near "."
```
Therefore, it is recommended to replace it with an underscore ( _ )
=> fix: PostgreSql create  index occur error

README.md, adapter.go, adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/issues/162#issuecomment-1126222024
Fix: https://github.com/casbin/gorm-adapter/issues/162
Fix: https://github.com/casbin/gorm-adapter/issues/145
=> fix: use TurnOffAutoMigrate instead of NewAdapterWithoutAutoMigrate

adapter.go
fixed the error occurred when savePolicy is called.
```
github.com/casbin/gorm-adapter/v3@v3.7.1/adapter.go:580 empty slice found
[3.402ms] [rows:0] INSERT INTO `casbin_rule` (`ptype`,`v0`,`v1`,`v2`,`v3`,`v4`,`v5`,`v6`,`v7`) VALUES 
empty slice found
```
=> fix: empty slice found error

adapter.go, adapter_test.go
Reverts casbin/gorm-adapter#157
Fix: https://github.com/casbin/gorm-adapter/issues/179
=> feat: revert "fix: add column v6, v7" and restore columns up to v5

README.md, adapter.go, adapter_test.go
Fix: https://github.com/casbin/gorm-adapter/issues/175
support transaction
Example: 
```golang
a := initAdapter(t, "mysql", "root:@tcp(127.0.0.1:3306)/", "casbin", "casbin_rule")
e, _ := casbin.NewEnforcer("examples/rbac_model.conf", a)
e.GetAdapter().(*Adapter).Transaction(e, func(e *casbin.Enforcer) error {
_, err := e.AddPolicy("jack", "data1", "write")
if err != nil {
return err
}
_, err = e.AddPolicy("jack", "data2", "write")
//err = errors.New("some error")
if err != nil {
return err
}
return nil
})
```
=> feat: support transaction

adapter.go, go.mod, go.sum
Since Casbin in the latest version has a nice feature, AddPermissionsForUser(), which can add multiple at the same time, I upgraded Casbin to v2.55.1.
Later, when using LoadPolicy(), I always found that the data in the database was not loaded into Casbin and no error was reported. After troubleshooting, I found that it was because loadPolicyLine was not returning an error message.
This error message was caused by a possible conflict in Casbin. In HasPolicyEx() it is required that the policy has 3 fields, otherwise an error message is thrown.
However, when using AddPermissionForUser(), it is possible to pass two parameters.
e.AddPermissionForUser("bob", "read")
So this submission has two main points.
1. Pre-check in LoadPolicy(), and throw an error message in advance if there is an error. …
=> feat: upgrade casbin to v2.55.1 and add preview feature

adapter.go
**Why**
We use casbin filtered adapter on closured level i.e new adapter created on every request instead on global level so that only relevant policies are loaded on every request. But creating a new gorm connection on every request would be not optimised. Hence wanted to expose a new filtered adapter which accepts existing gorm instance.
=> feat: New method for creating filtered adapter with existing gorm instance

adapter.go
Fix: https://github.com/casbin/gorm-adapter/issues/207
=> feat: use transaction in SavePolicy()

adapter.go
test code
```go
func TestAdapterTransactionOpertionBetweenMulDb(t *testing.T) {
//create new database
NewAdapter("mysql", "root:hsp@tcp(127.0.0.1:3306)/", "casbin")
NewAdapter("mysql", "root:hsp@tcp(127.0.0.1:3306)/", "casbin2")
dsn := "root:hsp@tcp(127.0.0.1:3306)/casbin"
dsn2 := "root:hsp@tcp(127.0.0.1:3306)/casbin2"
dbPool, err := InitDbResolver([]gorm.Dialector{mysql.Open(dsn), mysql.Open(dsn2)}, []string{"casbin", "casbin2"})
if err != nil {
panic(err)
}
//test independence between multi adapter
a1 := initAdapterWithGormInstanceByMulDb(t, dbPool, "casbin", "", "casbin_rule")
a1.AddPolicy("p", "p", []string{"t1", "t1", "t1"})
a2 := initAdapterWithGormInstanceByMulDb(t, dbPool, "casbin2", "", "casbin_rule2")
// add policies
a2.AddPolicies("p", "p", [][]string{{"t2", "t2", "t2"}, {"t3", …
```
=> fix: fix db switch error in transaction

adapter.go
Reverts casbin/gorm-adapter#226
=> fix: Revert "feat: limit transaction concurrency"

adapter.go
constructor NewAdapterByDBUseTableName should initialize transactionMu,
otherwise it will ~~panic~~ blocked due to that CAS when calling Transaction
Besides, a few other constructors also depend on NewAdapterByDBUseTableName,
if transactionMu is not initialized in NewAdapterByDBUseTableName,
it will blocked as well.
Besides, why not consider use sync.Once to initialize transactionMu?
=> feat: initialize transactionMu in NewAdapterByDBUseTableName

adapter.go
Fix: https://github.com/casbin/gorm-adapter/issues/239
=> feat: Remove underscores from the getFullTableName method when they are present

adapter.go, adapter_test.go
=> feat: add OnConflict=DoNothing on create operations
